---
name: Lint-Test Workflow

on:
  push:
    branches: [main, staging, dev]
  pull_request:
    branches: [main, staging, dev]

env:
  NODE_ENV: development
  # Use secrets for API keys
  EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}
  EXPO_PUBLIC_FIREBASE_AUTH_API_KEY: ${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_API_KEY }}
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  EXPO_PUBLIC_FIREBASE_AUTH_PROJECT_ID: ${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_PROJECT_ID }}
  EXPO_PUBLIC_FIREBASE_AUTH_APP_ID: ${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_APP_ID }}
  EXPO_PUBLIC_FIREBASE_AUTH_STORAGE_BUCKET: ${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_STORAGE_BUCKET }}
  EXPO_PUBLIC_FIREBASE_AUTH_MESSAGING_SENDER_ID: ${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_MESSAGING_SENDER_ID }}
  EXPO_PUBLIC_FIREBASE_AUTH_MEASUREMENT_ID: ${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_MEASUREMENT_ID }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6-beta

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          build: npx expo export -p web
          start: npx expo serve
          wait-on: 'http://localhost:8081'
          browser: chrome

      - name: Run linter
        run: npm run lint
